[package]
name = "deno-plugin"
version = "0.1.0"
authors = ["Ezeki Zibzibadze <ez@jok.io>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
futures = "0.3"
deno_core = "0.50.0"

[profile.release]
codegen-units = 1
lto = true
opt-level = 'z' # Optimize for size